version: '4'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: jimbarry_db
      MYSQL_USER: jimbarry
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - 3306:3306
    networks:
    - lamp-net
  www:
    depends_on:
      - db
    image: php8-apache-mysqlpdo:latest
    volumes:
      - "./www:/var/www"
    ports:
      - 80:80
      - 443:443
    networks:
    - lamp-net
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
    - lamp-net
networks:
  lamp-net:
    driver: bridge